if __name__ == "__main__":
    print("Hello world")
    zbior = set()
    print(zbior)
    zbior.add('a')
    print(zbior)
    zbior.add('b')
    print(zbior)
    zbior.add('a')
    print(len(zbior))
    print(zbior)