if __name__ == "__main__":
    nums = [1, 2, 3, 4]
    nums.remove(3)
    print(nums)
    nums.pop()
    print(nums)
    nums.pop(0)
    print(nums)
    nums.extend([3, 4])
    print(nums)
    nums.extend([])
    print(nums)
    nums.insert(0, 1)
    print(nums)
    nums.insert(2, "dwa-i-pół")
    print(nums)
    help(list)
    print("Hello world")
    print("mateuszjestgupi")
    print("jfnsofnow")